# Generated by Django 4.2.5 on 2023-11-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ordered", models.BooleanField(default=False)),
                ("date_added", models.DateField(auto_now=True)),
                ("date_ordered", models.DateField(null=True)),
                (
                    "product",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_code", models.CharField(max_length=15)),
                ("is_ordered", models.BooleanField(default=True)),
                ("date_ordered", models.DateTimeField(auto_now=True)),
                ("items", models.ManyToManyField(to="shopping_cart.orderitem")),
            ],
        ),
    ]
