# Generated by Django 4.2.5 on 2023-11-19 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shopping_cart", "0001_initial"),
        ("users", "0002_profile_delete_proflie"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
    ]
