# Generated by Django 4.2.5 on 2023-09-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=models.TextField(max_length=25), max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=25),
        ),
    ]
