# Generated by Django 4.2.5 on 2023-12-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_comment_product_comments_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="comments_set",
            field=models.ManyToManyField(blank=True, to="products.comment"),
        ),
    ]
