# Generated by Django 4.2.5 on 2023-12-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_product_comments_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="comments_set",
        ),
        migrations.AddField(
            model_name="product",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_comments",
                to="products.comment",
            ),
        ),
    ]
