# Generated by Django 4.2.5 on 2023-12-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_comments_set_product_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="comments",
        ),
        migrations.AddField(
            model_name="product",
            name="comments",
            field=models.ManyToManyField(
                blank=True, related_name="product_comments", to="products.comment"
            ),
        ),
    ]
